version: 2

orbs:
  cypress: cypress-io/cypress@1

jobs:
  build:
    docker:
      - image: circleci/node:12.9.1-browsers

    working_directory: ~/kids-python

    steps:
      
      - checkout

      - run:
          name: Install Circle CI Dependencies
          command: sudo apt-get update && sudo apt-get install xvfb libgtk-3-dev libnotify-dev libgconf-2-4 libnss3 libxss1 libasound2

      # - run:
      #     name: "Setup CYPRESS environment variables"
      #     command: |
      #       echo 'export CYPRESS_RECORD_KEY="4fc8874f-8ffb-4445-ad9b-ecb21142a871"' >> $BASH_ENV

      - run:
          name: "Setup AWS environment variables"
          command: |
            echo 'export AWS_BUCKET_NAME="kids-python"' >> $BASH_ENV

      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            - v1-dependencies-

      - run: yarn install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      - run: yarn lint
      - run: yarn size
      - run: yarn test
      # - run: yarn ci:cypress-run
      - run: yarn build

      - run: sudo apt-get install -y python-dev
      - run: sudo curl -O https://bootstrap.pypa.io/get-pip.py
      - run: sudo python get-pip.py
      - run: sudo pip install awscli --upgrade
      - run: aws --version
      - run: aws s3 ls
      - run: yarn deploy