version: 2
orbs:
  cypress: cypress-io/cypress@1
jobs:
  build:
    docker:
    - image: circleci/node:8.10
    working_directory: ~/kids-python
    steps:
    - checkout
    - run: 
        name: "Setup custom environment variables"
        command: echo 'export CYPRESS_RECORD_KEY="4fc8874f-8ffb-4445-ad9b-ecb21142a871"' >> $BASH_ENV
    - restore_cache:
        keys:
        - v1-dependencies-{{ checksum "package.json" }}
        - v1-dependencies-
    - run: yarn install
    - save_cache:
        paths:
        - node_modules
        key: v1-dependencies-{{ checksum "package.json" }}
    
    - run: yarn lint
    - run: yarn size
    - run: yarn test
    - run: yarn ci:cypress-run