version: 2

# commands:
#   sync:
#     description: "A simple encapsulation of doing an s3 sync"
#     parameters:
#       from:
#         type: string
#       to:
#         type: string
#       overwrite:
#         default: false
#         type: boolean
#     steps:
#       - run:
#           name: Deploy to S3
#           command: aws s3 sync << parameters.from >> << parameters.to >><<# parameters.overwrite >> --delete<</ parameters.overwrite >>"

orbs:
  # aws-s3: circleci/aws-s3@1.0.12
  cypress: cypress-io/cypress@1

jobs:
  build:
    docker:
      - image: circleci/node:12.9.1-browsers

    working_directory: ~/kids-python

    steps:
      
      - checkout

      - run:
          name: Install Circle CI Dependencies
          command: sudo apt-get update && sudo apt-get install xvfb libgtk-3-dev libnotify-dev libgconf-2-4 libnss3 libxss1 libasound2

      - run:
          name: "Setup Circle CI environment variables"
          command: |
            echo 'export CYPRESS_RECORD_KEY="4fc8874f-8ffb-4445-ad9b-ecb21142a871"' >> $BASH_ENV

      - run:
          name: "Setup AWS environment variables"
          command: |
            echo 'export AWS_ACCESS_KEY_ID="AKIAZ7P7HNIT7LYUHKNG"' >> $BASH_ENV
            echo 'export AWS_SECRET_ACCESS_KEY="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"' >> $BASH_ENV
            echo 'export AWS_REGION="us-east-1"' >> $BASH_ENV
            echo 'export AWS_BUCKET_NAME="kids-python"' >> $BASH_ENV

      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            - v1-dependencies-

      - run: yarn install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      - run: yarn lint
      - run: yarn size
      - run: yarn test
      - run: yarn ci:cypress-run
      - run: yarn build

      - run: sudo apt-get install -y python-dev
      - run: sudo curl -O https://bootstrap.pypa.io/get-pip.py
      - run: sudo python get-pip.py
      - run: sudo pip install awscli --upgrade
      - run: aws --version
      - run: aws s3 ls
      - run: 
          name: "Deploy to S3"
          command: |
              aws s3 sync dist/ s3://${AWS_BUCKET_NAME} --delete
              # aws cloudfront create-invalidation --distribution-id "${PRODUCTION_DISTRIBUTION_ID}" --paths /index.html